config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'try/ruby' => 'try#home'
  # post 'try/ruby' => 'try#save'
  post 'try/ruby/save' => 'try#save'
  get 'try/ruby/:code' => 'try#home'

  # to allow file extensions from github
  # http://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
  get 'try/ruby/github/:code' => 'try#github_code', :constraints => { :code => /[^\/]+/ }

  get 'turtle/draw' => 'turtle#draw'

  post 'turtle/draw/save' => 'turtle#save'
  get 'turtle/draw/:code' => 'turtle#draw'

  get 'repl/try' => 'repl#get'

  #get 'auth/github/callback' => 'github#callback'

  #get 'auth/github' => 'github#authorize'

  get "sessions/new"
  resources :users

  #resources :users
  # get "user_search", :to => "users#search"

  resources :sessions, :only => [:new, :create, :destroy]

  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  delete '/signout/:provider', :to => 'sessions#destroy'

  get   '/login', :to => 'sessions#new', :as => :login

  # For omniauth callback
  # Note that the /auth/github route is created by the middleware
  # https://medium.com/@woodpecker21/rails-6-how-to-implement-a-sign-in-with-github-ede6899cdf69
  # https://gist.github.com/biglovisa/aaf4099e5f8b4817dafb
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get,:post]

  match '/auth/failure', :to => 'sessions#failure', via: [:get,:post]

  get '/github/myfiles', :to => 'github#file_list'

  get 'lessons/:fname', :to => 'lessons#lesson'
  get 'lessons', :to => 'lessons#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  created_at         :datetime
#  updated_at         :datetime

class User < ActiveRecord::Base
  has_many :authorizations
  # attr_accessible :name

  validates :name, :presence => true, 
  :length => {:maximum => 50}
  
  def add_provider(auth_hash)
    # Check if the provider already exists, so we don't add it twice
    auth = nil
    if auth = authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      auth.update_credentials!(auth_hash)      
    else
      auth = Authorization.find_or_create(auth_hash, self)
      # Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
    auth
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, :only => [:edit, :update, :show]
  before_action :correct_user, :only => [:edit, :update, :show]
 
  def new
    @title = "Sign up"
    @user = User.new
  end
 
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end    
  
  def create
   @user = User.new(params[:user])
   
   if @user.save
     sign_in @user
     flash[:success] = "Signed in to CoderClub!"
     redirect_to @user
   else
     @title = "Sign up"
     render 'new'
   end
 end
 def edit
   @user = User.find(params[:id])
   # we know that @user is the current_user b/c of the before_filter
   @title = "Edit user"
 end
 def update
   @user = User.find(params[:id])
   if @user.update_attributes(user_params)
     flash[:success] = "Profile updated."
     redirect_to @user
   else
     @title = "Edit user"
     render 'edit'
   end
 end
  
  private 
  def authenticate
    deny_access unless signed_in? 
  end
 
  def correct_user
    @user = User.find(params[:id])
    redirect_to(index_path) unless current_user?(@user) || current_user.admin?
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 --> 
  <div class="col-md-1">
    <%= f.submit "Save", class: "btn btn-default btn-primary" %>
  </div> 
 
<% end %>

<div class="col-md-1">
  <%= button_to "Cancel", :back, class: "btn btn-default btn-primary", :method => :get %>
</div>

app/views/users/edit.html.erb
<div class="container"> 
  <h1>Editing User</h1>

  <%= render 'form' %>


</div>

app/views/users/show.html.erb
<div class="container" >

  <h3> Basic Info </h3>
  
  <div class="row" id="wrapper">
    <div class="col-md-2"> 
      Name:
    </div>
    <div class="col-md-2"> 
      <%= @user.name %>
    </div>
  </div>
  
  
  <div class="row" id="wrapper">
    <% if signed_in? and (@user == current_user) %>
    <div class="col-md-1">  
      <%= button_to "Sign Out", signout_path + "/github" , :method=>:delete, :class => "btn btn-primary"  %> 
    </div>
    <% end %>
    <div class="col-md-2">  
      <%= button_to "Change Info", edit_user_path(@user),  :action => 'edit', :id => @user, :class => "btn btn-primary", :method => :get %> 
    </div>
    
  </div>
</div>