config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'try/ruby' => 'try#home'
  # post 'try/ruby' => 'try#save'
  post 'try/ruby/save' => 'try#save'
  get 'try/ruby/:code' => 'try#home'

  # to allow file extensions from github
  # http://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
  get 'try/ruby/github/:code' => 'try#github_code', :constraints => { :code => /[^\/]+/ }

  get 'turtle/draw' => 'turtle#draw'

  post 'turtle/draw/save' => 'turtle#save'
  get 'turtle/draw/:code' => 'turtle#draw'

  get 'repl/try' => 'repl#get'

  #get 'auth/github/callback' => 'github#callback'

  #get 'auth/github' => 'github#authorize'

  get "sessions/new"
  resources :users

  #resources :users
  # get "user_search", :to => "users#search"

  resources :sessions, :only => [:new, :create, :destroy]

  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  delete '/signout/:provider', :to => 'sessions#destroy'

  get   '/login', :to => 'sessions#new', :as => :login

  # For omniauth callback
  # Note that the /auth/github route is created by the middleware
  # https://medium.com/@woodpecker21/rails-6-how-to-implement-a-sign-in-with-github-ede6899cdf69
  # https://gist.github.com/biglovisa/aaf4099e5f8b4817dafb
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get,:post]

  match '/auth/failure', :to => 'sessions#failure', via: [:get,:post]

  get '/github/myfiles', :to => 'github#file_list'

  get 'lessons/:fname', :to => 'lessons#lesson'
  get 'lessons', :to => 'lessons#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coderclub2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.4/codemirror.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.4/mode/ruby/ruby.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.32.0/codemirror.min.css" />
    <%= stylesheet_link_tag 'application', media: 'all' %>  <!-- %, 'data-turbolinks-track': 'reload' %>  -->
    <%= javascript_include_tag 'application' %> <!-- %, 'data-turbolinks-track': 'reload' %> --> 
<!-- for webpack: 
    < %= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' % >
    < %= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' % >
    -->
  </head>
<style>
    body {
        background-image: url(<%= asset_path "grey_computer_code.png" %>);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover; 
    }
</style>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  --> 
      <button id="navToggler" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'coder_club_logo_small.png' %></a>

    </div>
 
      <div class="collapse navbar-collapse" id="navbarSupportedContent" >
        <ul class="navbar-nav mr-auto">

        <li class="nav-item" ><%= link_to "TryRuby", try_ruby_path, class: 'nav-link' %> </li>
        <li class="nav-item" ><%= link_to "Turtle", turtle_draw_path, class: 'nav-link' %></li>
        <li class="nav-item" ><%= link_to "Lessons", lessons_path, class: 'nav-link' %></li>
        <% if signed_in? %>
            <li class="nav-item" >
              <%= link_to "Profile/Signout", current_user, class: 'nav-link' %>
            </li>
            <li class="nav-item" >
              <%= link_to "GithubFiles", "/github/myfiles", class: 'nav-link' %>
            </li>
         <% else %>
           <li class="nav-item" >
              <%= link_to "Login/Signup", signin_path, class: 'nav-link' %>
           </li>
         <% end %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
             Ruby links
             </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="http://kidsruby.com/"> Kids Ruby </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="https://try.ruby-lang.org/">Try Ruby</a>
            <a class="dropdown-item" href="https://opalrb.com/try/">Try Opal Ruby</a>
            <a class="dropdown-item" href="http://www.tutorialspoint.com/ruby/index.htm">Ruby Tutorial</a>
            <a class="dropdown-item" href="https://stackify.com/ruby-tutorials/">Top 30 Ruby Tutorials</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="http://ruby-doc.org/">Ruby Documentation </a>
          </div>
        </li>

        </ul> 
      </div>
    </nav>
    <div class="container">
     <div class="card border-0 shadow my-5" >
      <div class="card-body p-3 " style="height: 100%; width:100%" >
       <%= yield %>
      </div>
    </div>
   </div>
    <div class="card-footer text-muted "> <!-- fixed-bottom -->
      <div class="row" id="wrapper">
      
      </div>
   </div>

  </body>
</html>

app/views/layouts/blank_layout.html.erb
<%= yield %>
 